### ISSUE TITLE
Error messages not output

### ISSUE THREAD

**Issue by vernak2539** [avajs/gulp-ava#12]
Error messages are not being displayed when running AVA via gulp-ava.

Node: 0.10.44
NPM: 2.15.0
AVA: ^0.15.2
Gulp AVA: ^0.12.0

Gulp task is setup exactly as example in README, but using glob instead.

```js
return gulp.src('./test-node/**/*.js')
      .pipe(ava());
```

**Sample Test**
```js
test('initial registration of correct GET methods on server', t => {
  // Assert
  t.deepEqual(['/'], ['/logout', '/', '/harness']);

  // have also tried t.deepEqual(['/'], ['/logout', '/', '/harness'], 'message here');
});
```

**output from gulp task**
```bash
[11:23:40] Using gulpfile ~/Documents/WorkingEnvironment/ActiveAudiences/gulpfile.js
[11:23:40] Starting 'test'...
[11:23:40] Starting 'tests:node'...

/Users/avernacchia/Documents/WorkingEnvironment/ActiveAudiences/node_modules/gulp-ava/node_modules/gulp-util/lib/PluginError.js:73
  if (!this.message) throw new Error('Missing error message');
                           ^
Error: Missing error message
    at new PluginError (/Users/avernacchia/Documents/WorkingEnvironment/ActiveAudiences/node_modules/gulp-ava/node_modules/gulp-util/lib/PluginError.js:73:28)
    at DestroyableTransform.<anonymous> (/Users/avernacchia/Documents/WorkingEnvironment/ActiveAudiences/node_modules/gulp-ava/index.js:29:24)
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

**output from `node ./node_modules/ava/cli.js`**
```bash
> node ./node_modules/ava/cli.js --watch

   1 failed [11:26:44]

   1. index › initial registration of correct GET methods on server

  t.deepEqual(['/'], ['/logout', '/', '/harness'])

      Test.fn (index.js:24:5)
    handleMessage (child_process.js:322:10)
    Pipe.channel.onread (child_process.js:349:11)
```

**Comment by vernak2539** [comment]
@sindresorhus have you chance to take a look at this?

**Comment by sindresorhus** [comment]
I've fixed the error message not showing, but it was probably just hiding some other issue with your setup. Try master and report back.

**Comment by vernak2539** [comment]
@sindresorhus different output, but not what we're looking for. 

```
[16:55:51] Starting 'test:node'...
[16:55:53] 'test:node' errored after 1.56 s
[16:55:53] Error in plugin 'gulp-ava'
Message:
    Command failed:
Details:
    killed: false
    code: 1
    signal: null
```

**Comment by sindresorhus** [comment]
Adding adding `console.log(arguments)` above: https://github.com/avajs/gulp-ava/blob/15b380f03ff016bebff65b435e9357045c6d78c2/index.js#L30 and see what you get.

**Comment by vernak2539** [comment]
```
[17:10:18] Using gulpfile ~/Documents/WorkingEnvironment/ActiveAudiences/gulpfile.js
[17:10:18] Starting 'test:node'...
{ '0': { [Error: Command failed: ] killed: false, code: 1, signal: null },
  '1': 'TAP version 13\n# controllers › error-handlers › handling 404 errors when request accepts html\nok 1 - controllers › error-handlers › handling 404 errors when request accepts html\n# controllers › index › initial registration of correct GET methods on server\nok 2 - controllers › index › initial registration of correct GET methods on server\n# controllers › error-handlers › handling 404 errors when request accepts json\nok 3 - controllers › error-handlers › handling 404 errors when request accepts json\n# controllers › main › should register index controller\nok 4 - controllers › main › should register index controller\n# controllers › index › initial registration of correct POST methods on server\nok 5 - controllers › index › initial registration of correct POST methods on server\n# controllers › main › should register error-handler controller\nok 6 - controllers › main › should register error-handler controller\n# controllers › error-handlers › handling 404 errors when defaulting to plain text\nok 7 - controllers › error-handlers › handling 404 errors when defaulting to plain text\n# controllers › index › redirecting to / after POST to /login\nok 8 - controllers › index › redirecting to / after POST to /login\n# controllers › index › rendering index page after POST\nok 9 - controllers › index › rendering index page after POST\n# controllers › error-handlers › handling 500 errors\nok 10 - controllers › error-handlers › handling 500 errors\n# controllers › index › destorying session on logout\nok 11 - controllers › index › destorying session on logout\n# controllers › index › rendering index normally\nok 12 - controllers › index › rendering index normally\n# controllers › index › rendering harness page\nok 13 - controllers › index › rendering harness page\n# lib › i18n › should call api with proper url\nok 14 - lib › i18n › should call api with proper url\n# lib › i18n › should merge fallbacks into results\nok 15 - lib › i18n › should merge fallbacks into results\n# lib › i18n › should deliver response inside AMD wrapper\nok 16 - lib › i18n › should deliver response inside AMD wrapper\n# lib › i18n › should set response status to 500 if request to API request fails\nok 17 - lib › i18n › should set response status to 500 if request to API request fails\n# lib › i18n › should end response if API request fails\nok 18 - lib › i18n › should end response if API request fails\n# lib › user › should set proper fuel object in settings\nnot ok 19 - lib › user › should set proper fuel object in settings\n  ---\n    operator: ===\n    expected: true\n    actual: false\n    at: Test.fn (user.spec.js:36:2)\n  ...\n\n1..19\n# tests 19\n# pass 18\n# fail 1\n\n',
  '2': '' }
[17:10:27] 'test:node' errored after 8.45 s
[17:10:27] Error in plugin 'gulp-ava'
Message:
    Command failed:
Details:
    killed: false
    code: 1
    signal: null
```

**Comment by shinnn** [comment]
@vernak2539 Upgrade Node.js to >=4.0.0 and you can see the more useful error message included in the error object.

**Comment by sindresorhus** [comment]
Wut, why are you getting TAP output?

Try master now. It should now also show stdout.

**Comment by vernak2539** [comment]
So I had the code below in my package.json. I (wrongly) assumed `tap: true` was the default value due to the readme on the ava repo. Once removing that, I used v0.12.0 (no changes you made on master) and it output correctly. Sorry for the miscommunication, and thank you for the help. Much appreciated

```json
  "ava": {
    "files": [
      "test-node/**/*.spec.js"
    ],
    "concurrency": 5,
    "failFast": true
  },
```
